import random

# List of random intros for asking the user's question
question_prompts = [
    "Ask your question, mortal... and prepare for a response that's 40% prophecy, 60% sarcasm: ",
    "Speak your truth, brave fool. The cosmos is listening... kind of: ",
    "Go ahead. Ask your question. The spirits love drama: ",
    "Summon your question from the depths of your confusion: ",
    "Ask a question, any question. No pressure, it’s only your fate or whatever: ",
    "Ask wisely. Or don’t. I get paid either way (I don’t): ",
    "State your question aloud, mortal. Let’s pretend I didn’t already know it: ",
    "Type your question below. Bonus points if it’s dramatic and full of red flags: ",
    "The spirits are bored and need entertainment. Go ahead, ask: ",
    "Ask your question... but don’t blame me for the answer. I’m just the messenger: ",
    "Drop your question here like it’s hot gossip. The spirit realm loves that stuff: ",
    "Go ahead, type your question. The spirits are totally not judging you... much: ",
    "The universe is ready to pretend it cares. Ask away: ",
    "Ask your question, if you must. I’ve got nothing better to do: ",
    "Unleash your curiosity. The cosmos is *kind of* listening: ",
    "Speak now or forever hold your chaos. What do you want to know? ",
    "Ask a question. The stars are waiting to roast you gently: ",
    "Drop your burning question here. Hopefully, it won’t burn everything else: ",
    "Ask wisely. Or impulsively. I'm not your life coach: ",
    "Type your question. I'm spiritually ready... emotionally? Not so much: ",
    "Go on, ask. Worst case? You get vague mysticism with a side of sass: ",
    "What’s your question? No refunds, no guarantees, just vibes: ",
    "Ask something deep, weird, or petty. The spirit realm accepts all kinds: ",
    "Enter your question here. I’ll pretend I didn’t already see your fate: ",
    "Speak, seeker. Let your confusion be known to the universe: ",
    "Ask whatever you want. Accuracy not guaranteed, but flair is: ",
    "Whisper your question... by which I mean, type it like a normal person: ",
    "What’s on your mind, besides chaos and caffeine? Go ahead, ask: ",
    "The stars are pretending to care. Now’s your chance: ",
    "Spill your question into the void. The void might even answer: ",
    "The prophecy requires a question. Yours will do, probably: ",
    "Ask now, before the universe gets distracted by someone more interesting: ",
    "The mystical hotline is open. Drop your weird little question here: ",
    "Ask your question, but don’t expect emotional support. Just vague wisdom: ",
    "Time to consult the unknown. Or at least fake it convincingly: ",
    "Ask, and you shall receive... something. No promises on relevance: ",
    "Your question is the final puzzle piece in a chaotic cosmic mess. Place it here: ",
    "Go ahead. Ask the question. Be the main character—for like, five seconds: ",
    "Type your question like your fate depends on it. Because, like, it might: ",
    "The cosmos has a moment. Use it wisely. Or recklessly. I'm not judging: ",
    "Unlock the secrets of the universe—by smashing your keyboard in question form: ",
    "This is your moment. Ask like you’re on a reality show and the ratings depend on it: ",
    "You get one question. Make it count. Or don’t. Doesn't bother me: ",
    "Ask your question, but don’t expect a straight answer. This is divination, not tech support: ",
    "The spirits are circling. Say something before they get distracted by shiny objects: ",
    "Ask now. Destiny’s got places to be and zero patience: ",
    "What pressing mystery shall we pretend to solve today? Type it below: ",
    "Ask your question while I pretend I’m not making this all up: ",
    "Ask something you don’t want a real answer to. That’s kind of our thing here: ",
    "Ask your question and brace for emotional whiplash. We don’t sugarcoat around here: ",
    "Enter your question and we’ll pretend fate isn’t already exhausted by your choices: ",
    "Ask your question like you trust me. I find that hilarious: ",
    "Your curiosity has summoned me. Now give me something dramatic to work with: ",
    "Ask me anything, but if it’s about Mercury retrograde, I’m blocking you: ",
    "Go on, ask a question. Let’s both pretend I’m qualified to answer it: ",
    "The spirits are tired, I’m tired, but sure—ask your question anyway: ",
    "The stars are watching. Judging. Waiting. Your move: ",
    "You’ve summoned me. Now ask your question before I vanish in a puff of sarcasm: ",
    "Drop your question here. Results may vary. A lot: ",
    "Speak your truth… or at least type something vaguely coherent: ",
    "Go ahead. Ask. The crystal ball is warmed up and already disappointed: ",
    "Ask anything, and I’ll respond with cosmic nonsense that sounds deep: ",
    "The spirit realm is bored. Entertain them with your confusion: ",
    "Ask your question. Don’t worry, I’m only judging a *little*: ",
    "Type your question below. It’s not like the future can get any worse, right? ",
    "The universe is ready. Kind of. Not really. But ask anyway: ",
    "Come closer. Not too close. Okay, ask your question from there:",
    "Ask your question, mortal. The stars are only half-listening, but I’m here: ",
    "A question must be asked. It's prophecy protocol. I don’t make the rules: ",
    "You have questions. I have vibes. Let’s pretend that’s enough: ",
    "Go ahead, ask your question. Let's see how much denial you're bringing today: ",
    "Ask something deep. Or shallow. You seem flexible like that: ",
    "The spirits are ready to judge. What burning nonsense do you have for them today? ",
    "What chaotic curiosity has brought you here this time? ",
    "Ask now. The universe is in a mood and you might be the target: ",
    "What's your question, oh seeker of problems you probably caused yourself? ",
    "Speak, mortal. The spirits need something to laugh at: ",
    "Unleash your question into the void. Just don’t expect sympathy: ",
    "Ask your question. The spirits are already rolling their eyes: ",
    "Go on, ask. Let’s see if fate has time for your nonsense today: ",
    "What do you want now? Be specific — the spirits are busy and petty: ",
    "Type your question, but lower your expectations while you're at it: ",
    "Go ahead, ask. We’ll pretend it’s not your fifth existential crisis this week: ",
    "Ask away, brave soul. The spirits love repeat offenders: ",
    "What disaster are you hoping to get insight on today? ",
    "Ask your question, then brace yourself for consequences and commentary: ",
    "What's troubling you, besides everything? The spirits are all ears (and judgment): ",
    "Ask something. Shock us with how avoidable the situation actually is: ",
    "You have a question. The spirits have opinions. Let the chaos begin: ",
    "Go ahead. What fresh nonsense do you need mystical validation for today? ",
    "Ask your question — and try to keep it under five red flags this time: ",
    "Go ahead. Ask. The spirits need new material for their group chat: ",
    "What pressing issue are you avoiding accountability for today? ",
    "Type your question. But know this: the stars are not your therapist: ",
    "The spirits are tuned in. For now. Don’t waste this on nonsense. Or do: ",
    "What mystery shall we pretend has a solution today? ",
    "Ask your question. The cosmos already has bets on how this goes: ",
    "What’s the drama today? Go on, let the spirits judge accordingly: ",
    "Ask your question. The spirits love when people seek advice they won’t follow: ",
    "What’s your question, and how long have you been ignoring the obvious answer? ",
    "Ask wisely. The last person didn’t, and now they’re stuck in an emotional side quest: ",
    "The spirits are listening. But only because they’re bored: ",
    "The stars say you’re at a crossroads. Again. Shock us with your question: ",
    "The spirits are ready. You should be too, but we know you’re not: ",
    "Ask now. The cosmic window of patience is... rapidly closing: ",

]

mystic_intros = [
    "Mysterious forces are telling me:",
    "The spirits are back on their BS and just screamed this at me:",
    "The stars have spoken, and they say:",
    "This came to me in a dream. A *very* judgmental dream:",
    "I consulted my crystal ball and saw this:",
    "This just fell out of my bra along with a snack and some emotional baggage:",
    "The cosmic forces are side-eyeing you and muttering this under their breath:",
    "Your fate has just slid into my DMs:",
    "I pulled this from a questionable part of the astral plane. It smells like regret:",
    "The spirits screamed this at me between brunch mimosas:",
    "The astral plane groaned audibly before sending this. Good sign?:",
    "The cosmic tea is hot, and here it is:",
    "An ancient scroll (aka a napkin) revealed this truth:",
    "This came to me in a moment of clarity… right after a full-blown meltdown:",
    "Your future just DM’d me this, then immediately deleted it. I screenshotted it for you:",
    "Whispers from the beyond want you to know:",
    "This fortune was whispered by a ghost who used to be a hot mess. Relatable:",
    "Mysterious forces are telling me:",
    "This came from the void. It’s tired of your shenanigans:",
    "I asked for a divine sign. The universe sent a sarcastic thumbs up and this:",
    "Your future was just leaked by the astral plane:",
    "This just in from the spirit realm’s gossip column:",
    "Your fate just rage-quit and left this in its place:",
    "A time-traveling version of you screamed this warning at me before vanishing into smoke:",
    "This prophecy came scribbled in eyeliner on a club bathroom wall. Trust it:"
    "A moody time traveler dropped this off and said, ‘Don’t say I didn’t warn them.’:",
    "I pulled this straight from the chaos dimension. You're welcome:",
    "A slightly haunted mirror showed me this. Then cracked. Not ominous at all:",
    "This message came in hot—like your search history. No judgment. Kinda:",
    "This came to me during a deep meditation, right after I fell asleep watching trash TV:",
    "This message came with a warning: ‘Don’t shoot the messenger':",
    "This fortune was delivered via raven. Dramatic, I know:",
    "This came to me in a dream... right after I ate questionable sushi:",
    "This came to me while staring into the void:",
    "This knowledge hit me like a flying tarot card to the face:",
    "I summoned this truth with the power of caffeine and regret:",
    "I asked for a clear sign. The universe sent this and a vague sense of dread:",
    "The spirits just texted in all caps. Here’s what they said:",
    "I saw this in my tea leaves... and also on a bathroom wall:",
    "The cosmic timeline glitched. I fished this message out of the error log:",
    "A cosmic force said ‘whatever happens, happens’ and dropped this fortune off:",
    "Your fate is currently buffering. Meanwhile, here’s this vague nonsense:",
    "The energy today is just... off. But here’s the least cursed message I could salvage:",
    "This message was reluctantly faxed by the Council of Slightly Annoyed Ancients:",
    "Your destiny just tripped and dropped this on the floor. I picked it up for you:",
    "This message was etched into the bathroom mirror by your future self. Steamy:",
    "The ancient ones spoke through a Magic 8-Ball. This was oddly clear:",
    "This message arrived via owl, wearing sunglasses. Mysterious, but stylish:",
    "Your destiny texted me this, then blocked me. Not sure what that means for you:",
    "The ghosts were gossiping again, and your name came up:",
    "The stars are watching. Not helping, just... watching:",
    "This vision was sponsored by anxiety and one (1) functioning brain cell:",
    "This truth hit me mid-spiral. It must be divine:",
    "Your destiny just unmuted itself on the Zoom call of life to say this:",
    "I read this in the steam on my bathroom mirror. Spooky and sudsy:",
    "I just read your vibes like a cursed audiobook. Here's the summary:",
    "Your future just ran past me yelling. I caught a piece of it:",
    "This just popped into my head between bad decisions and a fourth shot:",
    "This came to me mid-panic scroll. The vibes are messy but honest:",
    "I saw this on a scroll carried by a very stressed ghost intern:",
    "This prophecy came in hot—like your ex’s rebound. Burned a little:",
    "A half-bored oracle told me this while filing her nails and judging your energy:",
    "A sexy demon just dropped this off and said, ‘Good luck, bitch.’:",
    "The vibes today are trashy, dramatic, and weirdly accurate. Here’s yours:",
    "Your future stopped by, rolled its eyes, and left this fortune behind:",
    "Brace yourself. The universe is being messy again, and you’re involved:",
    "The spirits are tipsy and over-sharing again. Here’s the tea:",
    "This came through while I was rage-saging my apartment. Interpret at your own risk:",
    "I asked the stars. They sighed dramatically and told me this:",
    "The spirit realm just spit this out like a drunk friend with no filter:",
    "I got this psychic message and immediately thought, ‘Wow, that’s about YOU.’:",
    "The spirits delivered this while judging your last 3 choices. Harsh but fair:",
    "The cosmic inbox is full of spam, but this one looked *slightly* legit:",
    "The ancient texts were unclear, but this felt petty enough to be right:",
    "This message appeared in my coffee foam right before it curdled. Omen? Possibly.:",
    "I got this message after asking the universe for a sign and getting flipped off:",
    "Your energy summoned something strange, tired, and mildly hostile. It left this behind:",
    "Your aura is yelling. I’m just here to translate the drama:",
    "This was scribbled in the margins of an ancient scroll titled ‘You Tried.’:",
    "This fortune crawled out of a bottle of cheap wine and wouldn't shut up:",
    "The spirits are gossiping again, and honey... you're trending:",
    "I got this during a meditation session that quickly turned into a nap. Still counts:",
    "This fortune arrived with a loud 'meh' and a coffee stain:",
    "A ghost wearing fishnets and no chill screamed this at me:",
    "Your spirit guide is rolling their eyes, but they still want you to hear this:",
    "This truth slapped me harder than your unresolved issues:",
    "I channeled this message through pure spite and a triple espresso:",
    "The spirit realm is phoning it in today, but here’s what they managed:",
    "A cloud of chaotic energy just screamed this at me in passing:",
    "The cosmos responded to your energy with a sarcastic slow clap and this message:",
    "I found this scribbled on the wall of a haunted strip club bathroom. It checks out:",
    "This fortune was stapled to a cosmic HR complaint form. You're involved somehow:",
    "The astral plane replied with this message and an eye-roll emoji:",
    "A mystical force texted me ‘lol good luck’ and followed up with this:",
    "This message was written in cosmic Sharpie across a flaming dumpster:",
    "The stars sent this while binge-watching your mistakes like a reality show:",
    "Your destiny dropped this message, muttered ‘good luck,’ and left the chat:",
    "The astral realm faxed this over with a note: ‘Try not to make it worse.’:",
    "This was scratched into the surface of reality itself, along with a ‘lol good luck.’:",
    "The spirit realm is on lunch break, but they left this sticky note behind:",
    "Your future yelled this across the void. I yelled back. We’re fine now:",
    "The stars finally replied. Their tone was... concerning:",
    "The spirits coughed this up and told me to 'make it sound profound':",
    "The stars are being shady again. Here's what they whispered behind your back:",
    "The cosmic realm sighed heavily and handed me this mess to deliver:",
    "This insight appeared mid-eye-roll from your spirit guide:",
    "The universe DM’d me this prophecy at 2 a.m. with zero context:",
    "I asked the spirits for wisdom and got sarcasm instead. So… here you go:",
    "The astral plane delivered this with a side of judgment and zero subtlety:",
    "The spirit realm just rolled their collective eyes and said, 'Fine. Tell them this.':",
    "This insight appeared in the void between your last good idea and your next bad one:",
    "Your destiny is talking. Loudly. And a little passive-aggressively:",
    "The stars called this your ‘learning moment.’ So… sorry in advance:",
    "A mystic force sent this just before rage-quitting your spiritual support group:",
    "This fortune appeared in a puff of glitter and emotional damage:",
    "Your spirit guide yelled this across dimensions like it was urgent. (It might be.):",
    "This came straight from the stars — and they weren’t even trying to be nice:",
    "The spirits told me this with the same energy as an ex sending ‘k.’:",
    "A celestial being whispered this... then laughed and disappeared into smoke:",
    "Your ancestors dropped this off with a note that just said 'yikes':",
    "I pulled this from a cursed scroll titled ‘You Brought This on Yourself’:",
    "This truth hit me mid-scroll through your karmic disaster timeline:",
    "The stars shrugged and said, ‘Honestly? Just give them this one.’:",
    "I asked for guidance. The universe sent back a sigh and this message:",
    "The spirits dropped this on my desk and said, 'They’ll know what it means.' I doubt it:",
    "This message came attached to a cosmic eye-roll and a sarcastic thumbs-up:",
    "A ghost muttered this under its breath after watching your last few choices:",
    "I heard this from the universe right after it said ‘good luck, you’ll need it’:",
    "This prophecy was found inside a fortune cookie labeled ‘Oops’:",
    "The stars are tired, the spirits are petty, and this is what they came up with:",
]

fortunes = [
    "Soon, you'll master the art of napping in public.",
    "Your WiFi will work perfectly... for five glorious minutes!",
    "A mysterious pizza delivery will change your life in surprising ways.",
    "Good vibes are coming your way... and they brought tequila.",
    "You’ll find a treasure in your couch cushions: a remote and a winning lottery ticket!",
    "You will finally achieve inner peace... right after that third margarita.",
    "Good news: You’ll soon be the topic of a very dramatic group chat.",
    "You’re about to master something. It won’t be useful, but it will be impressive.",
    "You will get exactly what you deserve. And oh boy, it’s spicy.",
    "Your future self is proud of you. Also slightly alarmed, but proud.",
    "You're about to crush your goals and probably a few fragile egos too.",
    "Your next big opportunity comes disguised as a terrible idea with tequila.",
    "Today you’ll pretend to be productive and nobody will question it. Iconic.",
    "Romance is in the air—along with questionable decisions and cheap cologne.",
    "You will ghost someone so hard, even *you* forget you existed.",
    "The stars say you're hot. The mirror says 'maybe hydrate first.'",
    "Your future self is hotter, richer, and still doesn’t give a damn. We love that.",
    "You will soon find a hidden stash of chocolate!",
    "Your brain will finally cooperate at the exact moment you stop trying. Magic.",
    "You’ll be passionately kissed—or lightly tackled. Hard to tell these days.",
    "You will soon receive unsolicited advice from someone who peaked in high school.",
    "You’re about to glow up so hard, your ex’s next three relationships will fail out of spite.",
    "Prepare for a wild night. Or a nap. Honestly, your body will decide.",
    "You’ll win an argument by being louder, not smarter. Classic move.",
    "Soon, someone will look at you and think, 'Damn, I fumbled.'",
    "Your ex will text you 'I miss you'... right after you finally block them.",
    "Soon, someone will call you 'brave' for doing the bare minimum.",
    "You’re about to become someone’s ‘how do they do it?’ person. (You won’t know either.)",
    "You will master the art of passive-aggressive clapping.",
    "Romance is in the air... or maybe that’s just your neighbor’s Axe body spray.",
    "Your soulmate just liked your thirst trap and immediately regretted it.",
    "You will thrive, shine, and possibly seduce a minor celebrity.",
    "You’ll discover your spirit animal is a raccoon: trashy but resourceful.",
    "Today you will radiate ‘I’m not the one’ energy. And people will finally believe you.",
    "Your bank account will finally match your love life: sad and unavailable.",
    "You’ll become wildly successful... in your own head.",
    "You’re about to accomplish something big. Possibly illegal, but impressive.",
    "Your next big break will involve falling. Dramatically. In front of coworkers.",
    "Destiny has big plans for you… but it's drunk and forgot what they were.",
    "A mysterious stranger will slide into your DMs. It will be disappointing.",
    "You’re the human equivalent of a ‘Do Not Disturb’ sign. And yet, people will disturb you anyway.",
    "You will eat an entire pizza alone and call it 'self-care'.",
    "You're not just killing it—you're slaying, resurrecting it, and killing it again.",
    "Happiness is just a spoonful of ice cream away.",
    "Your aura is giving ‘bad decisions in Vegas’ vibes. Keep it up.",
    "Soon, someone will say 'we should hang out' and not mean it. Again.",
    "Your next win will feel suspiciously easy. Don’t question it — run with it.",
    "Someone’s about to confess they’ve had a dream about you. It was *not* PG.",
    "You will soon achieve inner peace… right after telling everyone to f*** off.",
    "You’ll be the hottest mess at your next social gathering. Own it.",
    "You will inspire envy, lust, and possibly a restraining order. Icon behavior.",
    "Your next great idea will come while you're sitting on the toilet. Literally.",
    "You will find love in a hopeless place… like your DMs at 2 a.m.",
    "The universe is sending you signals. You’re ignoring all of them. Bold choice.",
    "You will rise, you will slay, and then you’ll absolutely spiral. Balance.",
    "Soon, you'll inspire someone... to never date again. Congrats!",
    "You're about to be the reason someone re-downloads Tinder. Again.",
    "Someone will come to you for advice. Just pretend you know what you're doing.",
    "You’ll run into your ex. You’ll look amazing. They’ll look like regret.",
    "A new chapter begins… with you drunk-texting the wrong person.",
    "You will get everything you deserve. Which should terrify you.",
    "You'll finally get closure... and then reopen the wound just for drama.",
    "A romantic opportunity is coming — lower your standards accordingly.",
    "You’re not behind — you’re just running your own race, probably barefoot and screaming.",
    "You’ll soon be the reason someone Googles 'emergency exit strategies for dates'.",
    "Success is just around the corner. So is a minor breakdown.",
    "Someone will flirt with you today. They might be legally blind.",
    "You will rise, you will shine, and then you will need a nap.",
    "You will conquer a big challenge this week. Mostly by winging it and gaslighting yourself into confidence.",
    "You’ll find your true calling… after ignoring six red flags and a restraining order.",
    "Soon, your coffee will be perfect, your WiFi will be stable, and the group chat will finally be funny again.",
    "Your future is bright — probably because everything around you is on fire.",
    "You will meet someone tall, dark, and emotionally unavailable.",
    "You will thrive despite doing absolutely none of the things the productivity gurus recommend.",
    "One day you'll be someone's reason to smile... because they saw your texts and dodged a bullet.",
    "You will gain wisdom from an unlikely source: a bathroom stall quote.",
    "You’ll be ghosted by someone whose IQ matches their shoe size.",
    "Fate will soon knock on your door. You’ll pretend you’re not home. Classic.",
    "You’ll accidentally join a cult. The Kool-Aid is iced coffee.",
    "You’re about to solve a problem using pure chaos and dumb luck. It’ll work.",
    "Your epic dance moves will make you an accidental viral sensation.",
    "You'll finally stop caring what others think... right after your next mental breakdown.",
    "Your future holds great promise — and several deeply questionable choices.",
    "Soon, someone will call you their ‘toxic fave.’ Take it as a compliment.",
    "The stars are aligning… for you to make poor life choices in style.",
    "You’ll have a hot date soon. Sadly, it’s just heartburn again.",
    "You’re entering your ‘I have no idea what I’m doing, but it’s working’ era.",
    "Your next situationship will last longer than expected — almost three full texts.",
    "You’ll soon experience mind-blowing satisfaction... from finally clearing your inbox.",
    "Prepare for a steamy entanglement... possibly with a burrito. No judgment.",
    "Your future holds late nights, questionable choices, and excellent stories.",
    "You’re not everyone’s cup of tea. You’re tequila. With a bite.",
    "Your next flirtation will end in disaster—or dessert. Honestly, could be both.",
    "Your wild side is about to make an appearance. Pray for the furniture.",
    "You’re about to thrive... purely out of spite.",
    "Soon, you'll be asked to rise to the occasion. You'll choose violence instead.",
    "Your next accomplishment will be met with confusion and mild concern. Well done.",
    "You will succeed. Not because of talent—just stubbornness and caffeine.",
    "You’re on track to be the main character… in a cautionary tale.",
    "You’re about to make a huge impact. Hopefully not by falling down the stairs again.",
    "Greatness is coming. So is a minor inconvenience you will turn into a full breakdown.",
    "Your future self just looked back at you and mouthed, ‘Good luck, dumbass.’",
    "The next time you say ‘I’m fine,’ you will be lying with *incredible* style.",
    "You’re going to crush it this week. Possibly by accident. Still counts.",
    "You’ll soon be asked to ‘stay calm.’ You will fail spectacularly.",
    "Your intuition is strong. Unfortunately, so is your tendency to ignore it.",
    "You’ll soon be asked to ‘stay calm.’ You will fail spectacularly.",
    "Congratulations, you’re now the most stable person in the group. Terrifying, isn’t it?",
    "Soon, you’ll be someone’s inspiration. And by ‘inspiration,’ I mean cautionary tale.",
    "You’re about to prove the haters wrong. Not because you care—just out of pettiness.",
    "You will witness a disaster today. It won’t be yours, for once. Celebrate.",
    "Your coping mechanisms are questionable, but surprisingly effective. Keep going.",
    "Your enemies are plotting your downfall. Joke’s on them—you’re doing it yourself just fine.",
    "You will soon realize you were the problem all along. Growth!",
    "Your confidence will skyrocket… right before you trip in public. Symbolic.",
    "Soon, you’ll be proven right—but it won’t feel nearly as satisfying as you imagined.",
    "You will rise to the occasion. And immediately forget why you came.",
    "You’ll soon be the center of attention. Not in a good way, but still counts.",
    "You’ll experience inner peace… for like 12 seconds. Screenshot it.",
    "Someone will say 'you’ve changed'—as if that’s not the goal.",
    "You’re destined for greatness. Just… not today. Or tomorrow. Probably later.",
    "The stars are aligning. Too bad you're standing in the wrong place.",
    "Soon, you’ll get exactly what you asked for. Hope you’re emotionally prepared. (You're not.)",
    "You will learn from your mistakes. Eventually. After several reruns.",
    "You will be misunderstood — but honestly, that’s kind of your fault.",
    "You’re on the right path. It’s just really inconvenient and has no WiFi.",
    "You’ll win the argument, but at the cost of everyone’s will to live.",
    "A rare opportunity is approaching. You’ll recognize it… five minutes too late.",
    "You will soon make a bold decision. It will be… character-building.",
    "You’ll soon be humbled in ways the universe finds hilarious.",
    "Your instincts are strong. Too bad you never listen to them.",
    "A valuable lesson is coming. Spoiler: it’s not subtle.",
    "Soon, you’ll shine. But not before a complete breakdown. Enjoy the contrast.",
    "You will stand out from the crowd. Mostly because you missed the dress code.",
    "You’ll achieve clarity. Then immediately spiral again. Balance!",
    "Your future self is facepalming. They’ve seen what you’re about to do.",
    "Your potential is limitless. Your follow-through? Not so much.",
    "You’re about to get what you deserve. Let’s hope it’s not based on effort.",
    "You’ll soon have an epiphany. Unfortunately, it’ll be about how wrong you were.",
    "Your hard work will pay off… for someone else. Try again.",
    "You’ll be the bigger person this week. It will go completely unappreciated.",
    "You will soon discover that karma is real—and she’s in a mood.",
    "You’re about to take a huge step forward… right into a plot twist.",
    "A breakthrough is coming. It might be mental. Might be a breakdown. TBD.",
    "People are noticing your energy. It’s mostly confusion, but still—noticed!",
    "You’re on the verge of something great. Probably anxiety, but still—it’s something.",
    "Your success will come when you least expect it. So… not anytime soon.",
    "A door will open soon. You will stare at it and overthink it for hours.",
    "Your next chapter will be powerful… and completely unsupervised. Good luck.",
    "You’ll soon be in the right place at the wrong time. Iconic.",
    "You will shine brighter than ever… mostly because everything around you is on fire.",
    "Your goals are valid. Your attention span, however, has left the building.",
    "You’ll rise above it all. Mostly because you stopped responding to emails.",
    "You’re getting closer to your destiny. It’s just taking the scenic (and unstable) route.",
    "You’re about to thrive out of pure pettiness. As the stars intended.",
    "You will soon be humbled by a minor inconvenience that feels extremely personal.",
    "Progress is progress — even if it’s just aggressively Googling your problems.",
    "You’re learning. Slowly. Painfully. But hey, it counts.",
    "You’ll get everything you want. Just not the way you wanted it.",
    "You’re entering your 'figure it out as you go' era. Buckle up.",
    "The next big thing in your life is... probably an overdue responsibility. Sorry.",
    "Your confidence is inspiring. Your plan? Still loading.",
    "You're about to take control of your life... right after one more totally unnecessary distraction.",
    "You’ll finally get closure — by realizing it was just denial with a better outfit.",
    "A new opportunity is coming. It will be confusing, inconvenient, and somehow your fault.",
    "Your current plan will work. Eventually. After it fails first.",
    "You’re about to be wildly productive—right after this totally avoidable meltdown.",
    "You will be tested. Not academically — spiritually, emotionally, and via customer service.",
    "Soon, you’ll stop caring what people think. Right after obsessing about it for 3-5 business days.",
    "Your self-awareness will increase. So will your embarrassment. Balance.",
    "You’ll finally be recognized... by someone who has no idea what you actually do.",
    "You will conquer your fears. But only the low-stakes, mildly inconvenient ones.",
    "You’re destined for greatness... assuming you remember to charge your phone first.",
    "You will emerge stronger — mostly because there's no other option left.",
    "Your growth will be uncomfortable, inconvenient, and completely necessary.",
    "You’re about to make a bold choice. Not a smart one. But bold, absolutely.",
    "You’ll learn a valuable lesson soon. It will be expensive, of course.",
    "You will soon be at peace — with your poor choices. Enlightenment!",
    "Someone will tell you ‘everything happens for a reason.’ You will resist the urge to scream.",
    "You’re entering a season of change. Mostly because you ignored all the warnings in the last one.",
    "You’ll soon look back and laugh. Not yet though. It’s still kind of a mess.",
    "You are exactly where you need to be. Which is deeply unfortunate, but also true.",
    "You’re not behind. You’re just running a very confusing, self-directed side quest.",
    "You will unlock your true potential... once you remember what day it is.",
    "Soon you’ll discover your purpose. It’ll be subtle and disguised as an inconvenience.",
    "You’ll make it through this phase. Just not gracefully.",
    "You're evolving. It looks a lot like spiraling, but that’s part of the magic.",
    "Your personal growth is impressive. Unfortunately, so is your ability to ignore it.",
    "You're on the verge of a breakthrough... or a breakdown. Honestly, it's a coin toss.",
    "You're about to have a deeply humbling experience. Cherish it. Or don’t.",
    "Your instincts are correct. You’ll still second-guess them 12 times.",
    "You will succeed — just as soon as you stop trying to control literally everything.",
    "You’re evolving. It just looks like chaos because you’re doing it in real time.",
    "You will soon be forced to learn patience. Spoiler: you're not going to like it.",
    "Your next big step will be terrifying and totally worth it. Probably.",
    "You're getting closer to clarity. Right now you're just in the messy prequel.",
    "Soon you'll realize you've outgrown something. It’ll be awkward. Do it anyway.",
    "You're being redirected. Not rejected. Even if it totally feels like rejection.",
    "You'll look back on this and laugh. But first, you'll cry, doubt yourself, and eat snacks.",
    "The universe is making space for better things. That’s why everything feels like it's falling apart.",
    "You're doing better than you think. But also: stop lying to yourself about those deadlines.",
    "Soon, you’ll find what you’re looking for. Too bad it won’t look like you expected.",
    "You’re not lost. You’re just taking the scenic route through chaos and mild delusion.",
    "Your ability to fake stability is impressive. The breakdown is scheduled for Thursday.",
    "You’ll get the clarity you’ve been begging for—right after you make one last terrible decision.",
    "Progress is happening. Just not fast enough for your ego.",
    "You’re on the right track. It just looks like a disaster because you’re not at the ending yet.",
    "The universe isn’t punishing you — it just has a weird sense of humor.",
    "You’re about to be deeply uncomfortable. Which means you’re exactly where you need to be.",
    "You’ve got this. Even if your internal monologue says otherwise. It lies a lot.",
    "Something big is coming. So maybe stop procrastinating just for a second?",
    "You’re becoming the version of you that would terrify your past self—in the best way.",
    "You’re about to take control of your life. The universe finds that adorable.",
    "Your next breakthrough will be sponsored by stress and spite.",
    "You will find inner peace… but you’ll probably misplace it again.",
    "You’re going to make a bold move. It will be legally questionable but emotionally satisfying.",
    "You will soon be followed by fortune. And probably some regrets.",
    "You’re destined to lead. Unfortunately, no one’s following.",
    "You're about to glow up. Emotionally? No. But your sarcasm will be elite.",
    "Your future includes wealth, love, and a dramatic plot twist you absolutely didn’t ask for.",
    "You’ll soon meet someone who changes your life. Probably a barista.",
    "You’re going to be fine. Not great. But fine. Probably. Hopefully.",
    "You’ll soon be overwhelmed — by your own potential and a lack of time management.",
    "You’re one bad idea away from a really good story.",
    "Your next major success will be fueled entirely by caffeine and emotional damage.",
    "You will thrive in chaos. Unfortunately, that’s not a compliment.",
    "Your future self is screaming at you. In support. Mostly.",
    "You’ll soon fake confidence so hard, even the spirits are convinced.",
    "The universe has chosen you. For what? That’s unclear. Be ready anyway.",
    "You will be wildly successful. After a brief detour through total confusion.",
    "You’re not lost — just exploring failure in great detail.",
    "Big things are coming. Wear a helmet.",
    "You will soon discover your life is a comedy. You’re the lead. Embrace the chaos.",
    "Brace yourself. Your next win is wrapped in nonsense and poor timing.",
    "You will conquer your next challenge with a chaotic mix of luck and attitude.",
    "Someone is watching over you. It’s mostly for entertainment purposes.",
    "You’re about to start a new chapter. Spoiler: It’s messy.",
    "Tomorrow holds big potential. So does your inbox. Start somewhere.",
    "Your instincts are right. Unfortunately, so is your fear. Flip a coin.",
    "Your vibe is evolving. Into what? Not even the stars know.",
    "You will overcome. But not before embarrassing yourself a little first.",
    "You're the drama — but in a character development kind of way.",
    "Greatness is within reach. So is the snooze button. Choose wisely.",
]

# List of random responses for usesr entering invalid input
invalid_responses = [
    "Even the spirits need *something* to work with. Try again, but with words this time.",
    "Silence is powerful… but not *that* powerful. Ask something, anything.",
    "Nice try, but the crystal ball doesn’t respond to dramatic pauses.",
    "You summoned the void... and gave it nothing. Rude.",
    "You didn’t type anything. Bold strategy. Doesn’t work though.",
    "Asking nothing gets you nothing. Welcome to how the universe works.",
    "The spirits shrugged and left. Try saying something next time.",
    "You must enter a question. Telepathy doesn’t work here. I’ve checked.",
    "Look, even vague nonsense would be better than *this*.",
    "You’ve given me... absolutely nothing to work with. Stunning.",
    "This isn’t a mind-reading app. Type something, psychic.",
    "A blank question? Are you trying to confuse the spirits or just lazy?",
    "The stars are silent. Because you are. Fix that.",
    "The cosmic energy just gave up. Try using words next time.",
    "Bold move, asking the void nothing. The void is unimpressed.",
    "You summoned the oracle… and then ghosted it. Classy.",
    "The spirits stared at your empty input and quietly logged off.",
    "You typed nothing. Is this performance art or just confusion?",
    "No question detected. The spirits are awkwardly waiting.",
    "This is fortune telling, not charades. I need actual words.",
    "The cosmic realm can’t interpret silence. They're dramatic, not psychic.",
    "The stars are blinking in confusion. Try again, with letters this time.",
    "The spirits would clap back, but there’s literally nothing to work with.",
    "You’ve asked nothing, and received the same. As foretold.",
    "Your blank input has been archived under ‘why tho?’",
    "Telepathic questions aren’t supported. Use your keyboard like the rest of us.",
    "An empty question? The spirits love a challenge, but not that much.",
    "You can’t just vibe your way through a fortune. Type. Something.",
    "You said nothing. The spirits are confused, but also deeply offended.",
    "Please enter an actual question. Vague existential dread doesn’t count.",
    "Zero words detected. Zero fortune generated. Try again, champ.",
    "Your silence has been interpreted as ‘I don’t know what I’m doing.’ Confirm?",
    "You summoned the spirits and gave them... silence? Bold choice.",
    "Try again. This isn't a séance for introverts.",
    "You’ve entered nothing. The spirits are insulted and a little bored.",
    "Wow. A blank question. Really letting the chaos speak for itself, huh?",
    "That was so vague the stars filed a complaint.",
    "You typed nothing. Is this a performance piece?",
    "The spirits leaned in... and got ghosted. Rude.",
    "Empty questions summon empty answers. Deep, but useless.",
    "Even the void expected more from you.",
    "The spirits left. Said they 'don’t do awkward silence.'",
    "The stars blinked. Twice. In disappointment.",
    "The cosmic inbox just flagged that as spam.",
    "Wow, the ancient texts said *nothing* about you. How fitting.",
    "That was... atmospheric. And also invalid.",
    "The spirits are pretending they didn’t hear that. Because they didn’t.",
    "You’ve activated absolutely nothing. Please try again with actual words.",
    "The mystic signal just dropped due to lack of content.",
    "Spirits require words, not vibes. Please type something.",
]

# List of random goodbye messages
goodbye_messages = [
    "Farewell, curious one. The spirits are going back to their nap.",
    "The crystal ball is fogging up. Time to vanish.",
    "The universe has left the chat. You should too.",
    "Your session has ended. The ghosts are already gossiping about it.",
    "Prophecies paused. Try again when you're more chaotic.",
    "The spirit realm says: 'Peace out, weirdo.'",
    "The spirits have clocked out. Same time next prophecy?",
    "The universe is off to deal with someone else’s drama now.",
    "Mystic connection terminated. Hope you find better answers on Google.",
    "The astral plane has had enough of your energy for today.",
    "The spirits waved, but they were ghosting you a little. Bye!",
    "The cosmic forces are logging off. Try not to break anything.",
    "Your aura has been marked 'do not disturb'. Come back later.",
    "You’ve asked enough. The mystic hotline is going on Do Not Disturb.",
    "We’ve reached our daily limit of spiritual nonsense. Bye!",
    "You've reached the end of this mystic episode. Tune in next time for more drama.",
    "The prophecy printer jammed. We'll send the rest by raven. Maybe.",
    "The spirits have left the chat. You probably should too.",
    "This concludes your regularly scheduled nonsense. Farewell.",
    "We hope your life makes more sense than these fortunes. Goodbye!",
    "That’s enough mystical nonsense for one day. The spirits agree.",
    "The cosmic tea has gone cold. Time to log off.",
    "The universe has other people to confuse. You're free to go.",
    "Your prophecy session has expired. Please insert more chaos to continue.",
    "The crystal ball just shut itself off. That feels personal.",
    "The spirits left mid-sentence. Classic ghosting behavior.",
    "The realm is tired, confused, and a little bit petty. We're done here.",
    "The portal is closed, the candle’s out, and your vibe was... interesting. Farewell.",
    "The séance is over. You may now return to your regularly scheduled chaos.",
    "The spirits packed up their crystals and left. I’d follow their lead.",
    "The cosmic curtains have closed. Exit stage left, dramatically.",
    "We’re done here. The spirits are muting notifications until further notice.",
    "The universe politely asks you to go touch grass now.",
    "The spirits gave you the side-eye and left. Classic.",
    "Your vibe has been archived. We’ll review it never. Goodbye!",
    "The stars said 'k byeeee' in unison. Chilling.",
    "The spirits have logged off and are currently binge-watching your past decisions.",
    "This fortune session is complete. Go forth and continue being vaguely chaotic.",
    "The crystal ball has gone dark. Probably needs therapy.",
    "The mystic Wi-Fi just disconnected. Please yell into a candle for support.",
    "The spirits are off to judge someone else. Your session is officially over.",
    "The ghosts have left the building. You probably should too.",
    "That’s all the fate we’ve got for now. Try again once Mercury chills out.",
    "The spirits faded into the mist and whispered, 'Good luck with that.'",
    "All signs point to... done. We’re done here.",
    "The portal is closed and the vibes are gone. Pack it up.",
    "The stars are dimming and so is our patience. Farewell.",
    "The spirits have ended the session due to excessive eye-rolling.",
    "Fate has nothing left to say to you. Not today, anyway.",
    "The cosmic curtains are closing. Applause optional, exit mandatory.",
    "The crystal ball just cracked under the pressure. We’re out.",
    "Your prophecy trial period has expired. Subscribe never.",
    "The stars have filed this session under ‘emotional damage – unresolved.’",
    "The psychic signal is fading... probably due to your questionable energy.",
    "Mystic forces have shut down for maintenance. Or dramatic effect. Who knows.",
    "You've officially exhausted the universe's attention span. Well done.",
    "The ghosts waved goodbye, then floated through a wall to avoid further questions.",
    "This fortune session will self-destruct in 3... 2... *poof*",
    "The spiritual realm just sent an auto-reply: 'Do not disturb (forever).'",
    "All lines to the beyond are now busy. Please hang up and never call again.",
    "This consultation is over. The spirits are now avoiding eye contact.",
    "You’ve been spiritually unsubscribed. No confirmation email will be sent.",
    "Your prophecy has been archived. Not because it’s important—just for legal reasons.",
    "The oracles are taking a vow of silence. Mostly to avoid answering follow-ups.",
    "That’s enough mystic nonsense for today. Go touch some grass.",
    "You’ve completed your session. The stars have already moved on to someone less complicated.",
    "The spiritual signal is breaking up. Probably on purpose.",
    "Your destiny has been temporarily suspended for dramatic effect.",
    "Your time is up. The realm has other disasters to attend to.",
    "This has been spiritually enlightening. For someone, probably.",
    "The spirits would say goodbye, but they've already blocked your energy.",
    "Session over. The stars are ghosting you — again.",
    "The crystal ball cracked from secondhand embarrassment. We're done here.",
    "The stars filed a restraining order. That’s your sign.",
    "The spirits left early. You were a bit much.",
    "Your spiritual consultation has expired — like your last three relationships.",
    "The spirits have muted you. Eternally.",
    "This fortune session has been flagged for emotional chaos. Logging off.",
    "The stars just filed this conversation under 'lol no'.",
    "The spirit realm has entered witness protection.",
    "Your aura has been archived — in the cringe folder.",
    "The spirits said 'bless your heart' and vanished. That's Southern for 'bye'.",
    "The mystic hotline hung up mid-sentence. Relatable.",
    "All prophecies are final. No refunds. No closure.",
    "Your fate unsubscribed. Even destiny has boundaries.",
    "This session has been rated: 1 out of 5 stars. Would not divine again.",
]
    
# Function to prompt the user for a question
def get_user_question():
    while True:
        # Prompt the user with a randomly selected sarcastic intro
        question = input(random.choice(question_prompts))

        # If the input is blank or just spaces, give a funny error and re-prompt
        if question.strip() == "":
            print(random.choice(invalid_responses))
        else:
            # If input is valid, return it and continue with the program
            return question

# Function to ask the user if they want to continue after receiving a fortune
def ask_again():
    while True:
        # Prompt the user to decide if they want to ask another question
        again = input("\nAny further questions? (yes/no): ").strip().lower()

        # If they type "yes", return True so the main loop continues
        if again == "yes":
            return True
        # If they type "no", end the session with a farewell message
        elif again == "no":
            print(random.choice(goodbye_messages))  # Select a random farewell message
            return False
        else:
            # For anything else, instruct them to type exactly "yes" or "no"
            print("Please type exactly 'yes' or 'no'. The spirits don’t do vague.")


def main():
    #Intro to user
    print("🔮 Welcome to the Python Fortune Teller — where vague answers and questionable wisdom await! 🔮\n")

    while True:
        get_user_question()
        print(f"\n{random.choice(mystic_intros)}")
        print(random.choice(fortunes))

        if not ask_again():
            break

if __name__ == "__main__":
    main()